### ISSUE TITLE
请帮忙看看什么原因，谢谢

### ISSUE THREAD

**Issue by DevilLeven** [jinhuiWong/vux-2.0#10]
import {FlexboxItem,Flexbox} from 'vuxx/src/components'

 ERROR  Failed to compile with 1 errors                                                                                                                           2:48:31 PM

This dependency was not found:

* vuxx/src/components in ./~/.6.4.0@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./src/components/home.vue

To install it, you can run: npm install --save vuxx/src/components

**Comment by jinhuiWong** [comment]
检查一下install有没成功

**Comment by DevilLeven** [comment]
当我引入 
 import Flexbox from 'vuxx/src/components/flexbox/flexbox.vue'
    import FlexboxItem from 'vuxx/src/components/flexbox/flexbox-item.vue'
    import Group from 'vuxx/src/components/group'
这三个是没有问题的，但是当我再加一个
import Picker from 'vuxx/src/components/picker'
就报错：
These relative modules were not found:

* ./scroller in ./~/.6.4.1@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./~/.0.1.7@vuxx/src/components/picker/index.vue
* ../flexbox in ./~/.6.4.1@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./~/.0.1.7@vuxx/src/components/picker/index.vue
* ./chain in ./~/.6.4.1@babel-loader/lib!./~/.11.1.4@vue-loader/lib/selector.js?type=script&index=0!./~/.0.1.7@vuxx/src/components/picker/index.vue
是版本不兼容的问题吗 @jinhuiWong

**Comment by jinhuiWong** [comment]
你用的webpack和vue-loader是什么版本的
