### ISSUE TITLE
Confirm绑定点击事件的时候this.$vux.confirm.show({})报错confirm未定义

### ISSUE THREAD

**Issue by Devil10261** [jinhuiWong/vux-2.0#11]
在方法中打印了this.$vux也同样找不到undefined

参考的是vux官网demo

v-model绑定开关没有问题，但是绑定v-on:click就汇报上边错误
用其它组件很正常：
vue和webpack等都是最新新版本

![qq 20170320175820](https://cloud.githubusercontent.com/assets/26298419/24095193/e5835c76-0d96-11e7-8a4a-9d3514c0d85b.png)
![qq 20170320175802](https://cloud.githubusercontent.com/assets/26298419/24095195/e7fa08b0-0d96-11e7-85fb-0e9ae0c84af2.png)

**Comment by Devil10261** [comment]
有个地方忘改了
应该是console.log(this.$vux)；会报undefined

**Comment by Devil10261** [comment]
有答案可以发我邮箱 892923314@qq.com

**Comment by jinhuiWong** [comment]
vux的问题移步到 https://github.com/airyland/vux/issues
