### ISSUE TITLE
求助：webpack  打包的时候报如下错误

### ISSUE THREAD

**Issue by pysjp** [jinhuiWong/vux-2.0#4]
ERROR in ./~/vuxx/src/components/tab/tab.vue
Module not found: Error: Can't resolve '[object Object]' in '/Users/jerry/Documents/html5/device-ui/node_modules/vuxx/src/components/tab'
 @ ./~/vuxx/src/components/tab/tab.vue 5:0-201
 @ ./~/vuxx/src/components/tab/index.js
 @ ./~/vuxx/src/components/index.js
 @ ./~/babel-loader/lib!./~/vue-loader/lib/selector.js?type=script&index=0!./src/pages/test/app.vue
 @ ./src/pages/test/app.vue
 @ ./src/pages/test/index.js
 @ multi test

**Comment by jinhuiWong** [comment]
这个格式没法看啊，发详细点吧
