### ISSUE TITLE
打包没错, 运行出错!

### ISSUE THREAD

**Issue by hookehuyr** [jinhuiWong/vux-2.0#5]
webpack 打包到是没有错, 但是 npm run dev 跑起来的时候
[Error] TypeError: undefined is not an object (evaluating 'vnode.isRootInsert = !nested')

从 NPM 上把 vuxx 拉下来跑 依然报错

**Comment by jinhuiWong** [comment]
vue的2.1.7版本问题，解决办法可以参考
https://github.com/monterail/vue-multiselect/issues/179
